#!/bin/sh
set -eu

if [ -n "${NYAUTH_RUNTIME_DB_PASSWORD_FILE:-}" ]; then
    NYAUTH_RUNTIME_DB_PASSWORD_VALUE="$(cat "$NYAUTH_RUNTIME_DB_PASSWORD_FILE")"
else
    NYAUTH_RUNTIME_DB_PASSWORD_VALUE="${NYAUTH_RUNTIME_DB_PASSWORD:?set NYAUTH_RUNTIME_DB_PASSWORD or NYAUTH_RUNTIME_DB_PASSWORD_FILE}"
fi
export NYAUTH_RUNTIME_DB_PASSWORD_VALUE

psql --set=ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<'SQL'
\getenv runtime_password NYAUTH_RUNTIME_DB_PASSWORD_VALUE
SELECT format('CREATE ROLE nyauth_runtime LOGIN PASSWORD %L NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS', :'runtime_password')
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nyauth_runtime') \gexec
SELECT format('ALTER ROLE nyauth_runtime LOGIN PASSWORD %L NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS', :'runtime_password') \gexec
SELECT format('GRANT CONNECT ON DATABASE %I TO nyauth_runtime', current_database()) \gexec
REVOKE CREATE ON SCHEMA public FROM nyauth_runtime;
GRANT USAGE ON SCHEMA public TO nyauth_runtime;
ALTER DEFAULT PRIVILEGES FOR ROLE nyauth_migrator IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO nyauth_runtime;
ALTER DEFAULT PRIVILEGES FOR ROLE nyauth_migrator IN SCHEMA public
    GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO nyauth_runtime;
ALTER DEFAULT PRIVILEGES FOR ROLE nyauth_migrator IN SCHEMA public
    GRANT EXECUTE ON FUNCTIONS TO nyauth_runtime;
ALTER DEFAULT PRIVILEGES FOR ROLE nyauth_migrator IN SCHEMA public
    GRANT USAGE ON TYPES TO nyauth_runtime;
SQL

unset NYAUTH_RUNTIME_DB_PASSWORD_VALUE
