#!/bin/sh
set -eu

if [ -n "${NYAUTH_RUNTIME_DB_PASSWORD_FILE:-}" ]; then
    NYAUTH_RUNTIME_DB_PASSWORD_VALUE="$(cat "$NYAUTH_RUNTIME_DB_PASSWORD_FILE")"
else
    NYAUTH_RUNTIME_DB_PASSWORD_VALUE="${NYAUTH_RUNTIME_DB_PASSWORD:?set NYAUTH_RUNTIME_DB_PASSWORD or NYAUTH_RUNTIME_DB_PASSWORD_FILE}"
fi

NYAUTH_RUNTIME_DB_ROLE_VALUE="${NYAUTH_DATABASE_RUNTIME_ROLE:-nyauth_runtime}"
case "$NYAUTH_RUNTIME_DB_ROLE_VALUE" in
    ""|[0-9]*|*[!A-Za-z0-9_]*)
        echo "NYAUTH_DATABASE_RUNTIME_ROLE must match [A-Za-z_][A-Za-z0-9_]*" >&2
        exit 1
        ;;
esac
if [ "${#NYAUTH_RUNTIME_DB_ROLE_VALUE}" -gt 63 ]; then
    echo "NYAUTH_DATABASE_RUNTIME_ROLE must not exceed 63 ASCII characters" >&2
    exit 1
fi
if [ "$NYAUTH_RUNTIME_DB_ROLE_VALUE" = "$POSTGRES_USER" ]; then
    echo "NYAUTH_DATABASE_RUNTIME_ROLE must differ from POSTGRES_USER" >&2
    exit 1
fi

export NYAUTH_RUNTIME_DB_PASSWORD_VALUE NYAUTH_RUNTIME_DB_ROLE_VALUE

psql --set=ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<'SQL'
\getenv runtime_password NYAUTH_RUNTIME_DB_PASSWORD_VALUE
\getenv runtime_role NYAUTH_RUNTIME_DB_ROLE_VALUE
SELECT format('CREATE ROLE %I LOGIN PASSWORD %L NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS', :'runtime_role', :'runtime_password')
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'runtime_role') \gexec
SELECT format('ALTER ROLE %I LOGIN PASSWORD %L NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS', :'runtime_role', :'runtime_password') \gexec
SELECT format('GRANT CONNECT ON DATABASE %I TO %I', current_database(), :'runtime_role') \gexec
SELECT format('REVOKE CREATE ON SCHEMA public FROM %I', :'runtime_role') \gexec
SELECT format('GRANT USAGE ON SCHEMA public TO %I', :'runtime_role') \gexec
SELECT format('ALTER DEFAULT PRIVILEGES FOR ROLE %I IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO %I', current_user, :'runtime_role') \gexec
SELECT format('ALTER DEFAULT PRIVILEGES FOR ROLE %I IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO %I', current_user, :'runtime_role') \gexec
SELECT format('ALTER DEFAULT PRIVILEGES FOR ROLE %I IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO %I', current_user, :'runtime_role') \gexec
SELECT format('ALTER DEFAULT PRIVILEGES FOR ROLE %I IN SCHEMA public GRANT USAGE ON TYPES TO %I', current_user, :'runtime_role') \gexec
SQL

unset NYAUTH_RUNTIME_DB_PASSWORD_VALUE NYAUTH_RUNTIME_DB_ROLE_VALUE
