package server

import "strings"

const apiErrorCodeRequestFailed = "request_failed"

var apiErrorCodesByMessage = map[string]string{
	"invalid credentials":                                                                "auth.invalid_credentials",
	"current password is incorrect":                                                      "auth.current_password_incorrect",
	"authentication required":                                                            "auth.authentication_required",
	"recent authentication is required":                                                  "auth.recent_authentication_required",
	"password reauthentication is unavailable":                                           "auth.password_reauthentication_unavailable",
	"password login is not available for this account":                                   "auth.password_login_unavailable",
	"a local password is already configured":                                             "auth.password_already_configured",
	"reauthentication failed":                                                            "auth.reauthentication_failed",
	"reauthentication session could not be updated":                                      "auth.reauthentication_session_update_failed",
	"csrf_validation_failed":                                                             "security.csrf_validation_failed",
	"invalid csrf token":                                                                 "security.csrf_validation_failed",
	"password change required":                                                           "account.password_change_required",
	"email verification is required before signing in":                                   "account.email_verification_required",
	"registration is closed":                                                             "registration.closed",
	"invite code is required":                                                            "registration.invite_required",
	"invalid or expired invite code":                                                     "registration.invite_invalid",
	"username or email is already taken":                                                 "registration.identity_conflict",
	"username is already taken":                                                          "user.username_conflict",
	"email is already taken":                                                             "user.email_conflict",
	"email domain is not allowed":                                                        "registration.email_domain_not_allowed",
	"too many registration attempts":                                                     "registration.rate_limited",
	"registration is temporarily unavailable":                                            "registration.unavailable",
	"registration temporarily unavailable":                                               "registration.unavailable",
	"registration requires email delivery, which is not configured":                      "registration.mail_not_configured",
	"mail settings are temporarily unavailable":                                          "mail.settings_unavailable",
	"mail configuration is invalid":                                                      "mail.configuration_invalid",
	"mail configuration version was not found":                                           "mail.version_not_found",
	"mail settings changed; reload and try again":                                        "mail.revision_conflict",
	"a successful candidate test is required":                                            "mail.test_required",
	"the successful candidate test has expired":                                          "mail.test_expired",
	"no previous mail configuration is available":                                        "mail.rollback_unavailable",
	"mail is already disabled":                                                           "mail.already_disabled",
	"close self-registration before disabling mail":                                      "mail.registration_must_close",
	"too many mail settings operations":                                                  "mail.rate_limited",
	"a verified administrator email is required for template tests":                      "mail.template_test_recipient_unverified",
	"test recipient must match the administrator's verified email":                       "mail.template_test_recipient_mismatch",
	"mail delivery is unavailable":                                                       "mail.delivery_unavailable",
	"test email could not be delivered":                                                  "mail.template_test_delivery_failed",
	"connect_timeout must be a valid duration":                                           "mail.connect_timeout_invalid",
	"send_timeout must be a valid duration":                                              "mail.send_timeout_invalid",
	"plain smtp is forbidden in production":                                              "mail.plain_forbidden",
	"public_base_url must use https in production":                                       "mail.public_base_url_insecure",
	"email is invalid":                                                                   "account.email_invalid",
	"mfa challenge expired":                                                              "mfa.challenge_expired",
	"mfa challenge temporarily unavailable":                                              "mfa.challenge_unavailable",
	"mfa verification temporarily unavailable":                                           "mfa.verification_unavailable",
	"too many mfa attempts":                                                              "mfa.rate_limited",
	"invalid mfa code":                                                                   "mfa.code_invalid",
	"invalid totp code":                                                                  "mfa.totp_invalid",
	"unsupported mfa method":                                                             "mfa.method_unsupported",
	"account changed; sign in again":                                                     "auth.account_changed",
	"mfa enrollment is required; contact an administrator":                               "mfa.enrollment_required",
	"unmet authentication requirements":                                                  "oauth.unmet_authentication_requirements",
	"invalid or expired authorization request":                                           "oauth.authorization_request_invalid",
	"totp enrollment is disabled":                                                        "mfa.totp_enrollment_disabled",
	"totp is already enrolled":                                                           "mfa.totp_already_enrolled",
	"totp enrollment must be restarted":                                                  "mfa.totp_enrollment_restart_required",
	"totp is not enrolled":                                                               "mfa.totp_not_enrolled",
	"mfa is required for active administrators":                                          "mfa.required_for_admins",
	"all active administrators must enroll mfa before it can be required":                "mfa.admin_enrollment_incomplete",
	"totp must remain enabled while administrator mfa is required":                       "mfa.totp_required_by_policy",
	"passkey login temporarily unavailable":                                              "passkey.login_unavailable",
	"passkey ceremony temporarily unavailable":                                           "passkey.ceremony_unavailable",
	"passkey verification temporarily unavailable":                                       "passkey.verification_unavailable",
	"passkey reauthentication temporarily unavailable":                                   "passkey.reauthentication_unavailable",
	"passkey registration temporarily unavailable":                                       "passkey.registration_unavailable",
	"passkey registered; please sign in again":                                           "passkey.registered_sign_in_required",
	"passkey removed; please sign in again":                                              "passkey.removed_sign_in_required",
	"passkey verification failed":                                                        "passkey.verification_failed",
	"passkey registration could not be verified":                                         "passkey.registration_invalid",
	"passkey enrollment is disabled":                                                     "passkey.enrollment_disabled",
	"this passkey is already registered":                                                 "passkey.already_registered",
	"no passkey is registered":                                                           "passkey.none_registered",
	"passkey not found":                                                                  "passkey.not_found",
	"passkey name must contain 1 to 64 characters":                                       "passkey.name_invalid",
	"add a password, provider identity, or another passkey before removing this passkey": "passkey.last_authenticator",
	"webauthn ceremony id is required":                                                   "passkey.ceremony_id_required",
	"webauthn ceremony expired":                                                          "passkey.ceremony_expired",
	"webauthn ceremony is invalid":                                                       "passkey.ceremony_invalid",
	"too many passkey ceremonies":                                                        "passkey.rate_limited",
	"avatar image exceeds 8 mib":                                                         "avatar.too_large",
	"avatar media type must be jpeg, png, or static webp":                                "avatar.media_type_invalid",
	"animated webp avatars are not supported":                                            "avatar.animated_webp_unsupported",
	"avatar image dimensions are invalid":                                                "avatar.dimensions_invalid",
	"user avatar upload must be square after browser crop":                               "avatar.square_required",
	"too many avatar operations":                                                         "avatar.rate_limited",
	"avatar operation is temporarily unavailable":                                        "avatar.operation_unavailable",
	"avatar storage is temporarily unavailable":                                          "avatar.storage_unavailable",
	"media operation is temporarily unavailable":                                         "media.operation_unavailable",
	"media processing is temporarily unavailable":                                        "media.processing_unavailable",
	"too many media operations":                                                          "media.operation_rate_limited",
	"media settings are temporarily unavailable":                                         "media.settings_unavailable",
	"media storage configuration is invalid":                                             "media.configuration_invalid",
	"media settings changed; reload and try again":                                       "media.revision_conflict",
	"media storage candidate was not found":                                              "media.candidate_not_found",
	"a recent successful media storage test is required":                                 "media.test_required",
	"a media storage migration is already active":                                        "media.migration_active",
	"media storage migration was not found":                                              "media.migration_not_found",
	"media writes must be paused before migration":                                       "media.migration_not_paused",
	"active instances are still preparing the media storage candidate":                   "media.instances_not_ready",
	"local media fallback is not configured":                                             "media.fallback_not_configured",
	"local media fallback is already active":                                             "media.fallback_already_active",
	"local media fallback migration requires a single active instance":                   "media.fallback_requires_single_instance",
	"local media fallback is unavailable":                                                "media.fallback_unavailable",
	"media writes are still draining; retry after service control is applied":            "media.draining",
	"clear the current maintenance expiry before starting media migration":               "media.maintenance_expiry",
	"too many media settings operations":                                                 "media.rate_limited",
	"application limit reached":                                                          "client.quota_exceeded",
	"self-service client creation is disabled":                                           "client.self_service_disabled",
	"oauth client policy changed; reload and retry":                                      "client.policy_changed",
	"service capability is paused":                                                       "service.capability_paused",
	"settings revision conflict":                                                         "settings.revision_conflict",
	"rate limit disable confirmation is required":                                        "settings.disable_confirmation_required",
	"audit retention confirmation is required":                                           "settings.retention_confirmation_required",
	"settings are temporarily unavailable":                                               "settings.unavailable",
	"failed to list login history":                                                       "login_history.unavailable",
	"failed to list trusted devices":                                                     "trusted_device.list_unavailable",
	"invalid trusted device id":                                                          "trusted_device.id_invalid",
	"trusted device not found":                                                           "trusted_device.not_found",
	"failed to revoke trusted device":                                                    "trusted_device.revoke_unavailable",
	"failed to revoke trusted devices":                                                   "trusted_device.revoke_unavailable",
	"too many settings operations":                                                       "settings.rate_limited",
	"observability settings are temporarily unavailable":                                 "observability.settings_unavailable",
	"failed to store observability settings":                                             "observability.store_failed",
	"log_level must be info, warn, or error":                                             "observability.log_level_invalid",
	"debug_until must be between 1 minute and 24h0m0s from now":                          "observability.debug_until_invalid",
	"otlp settings revision conflict":                                                    "telemetry.revision_conflict",
	"otlp candidate changed; reload settings":                                            "telemetry.candidate_changed",
	"a recent successful otlp candidate test is required":                                "telemetry.test_required",
	"the successful otlp candidate test has expired":                                     "telemetry.test_expired",
	"no previous otlp configuration is available":                                        "telemetry.rollback_unavailable",
	"otlp export is already disabled":                                                    "telemetry.already_disabled",
	"otlp authorization cannot be inherited":                                             "telemetry.authorization_inheritance",
	"otlp settings are temporarily unavailable":                                          "telemetry.settings_unavailable",
	"export_interval must be a valid duration":                                           "telemetry.export_interval_invalid",
	"timeout must be a valid duration":                                                   "telemetry.timeout_invalid",
	"otlp configuration was activated but could not be applied on this instance":         "telemetry.activation_apply_failed",
	"otlp rollback was stored but could not be applied on this instance":                 "telemetry.rollback_apply_failed",
	"otlp disable was stored but could not be applied on this instance":                  "telemetry.disable_apply_failed",
	"service control revision conflict":                                                  "service_control.revision_conflict",
	"registration settings conflict with service control":                                "service_control.registration_conflict",
	"service control dependency violation":                                               "service_control.dependency_violation",
	"invalid service control settings":                                                   "service_control.invalid_settings",
	"service control is temporarily unavailable":                                         "service_control.unavailable",
	"too many service control operations":                                                "service_control.rate_limited",
	"human verification is required":                                                     "human_verification.required",
	"human verification failed":                                                          "human_verification.failed",
	"human verification is temporarily unavailable":                                      "human_verification.unavailable",
	"human verification provider is unavailable":                                         "human_verification.provider_unavailable",
	"human verification test was rejected":                                               "human_verification.test_rejected",
	"human verification settings are unavailable":                                        "human_verification.settings_unavailable",
	"human verification settings revision conflict":                                      "human_verification.revision_conflict",
	"human verification candidate changed":                                               "human_verification.candidate_changed",
	"a human verification secret is required":                                            "human_verification.secret_required",
	"a successful human verification candidate test is required":                         "human_verification.test_required",
	"the successful human verification candidate test has expired":                       "human_verification.test_expired",
	"no previous human verification configuration is available":                          "human_verification.rollback_unavailable",
	"no active human verification configuration is available":                            "human_verification.enable_unavailable",
	"human verification is already disabled":                                             "human_verification.already_disabled",
	"human verification is already enabled":                                              "human_verification.already_enabled",
	"human verification settings operation failed":                                       "human_verification.operation_failed",
	"announcement revision conflict":                                                     "announcement.revision_conflict",
	"announcement state does not allow this operation":                                   "announcement.invalid_transition",
	"announcement not found":                                                             "announcement.not_found",
}

func apiErrorCodeForMessage(message string) string {
	normalized := strings.ToLower(strings.TrimSpace(message))
	if strings.Contains(normalized, "password must be valid utf-8 and 12 to 1024 bytes") {
		return "auth.password_policy_violation"
	}
	if code := apiErrorCodesByMessage[normalized]; code != "" {
		return code
	}
	if strings.HasPrefix(normalized, "invalid otlp configuration:") {
		return "telemetry.configuration_invalid"
	}
	if strings.HasPrefix(normalized, "invalid human verification configuration:") {
		return "human_verification.configuration_invalid"
	}
	if strings.HasPrefix(normalized, "invalid oauth client:") {
		return "client.configuration_invalid"
	}
	if strings.HasPrefix(normalized, "invalid security settings:") {
		return "settings.configuration_invalid"
	}
	if strings.HasPrefix(normalized, "mail_backlog_count must be between ") ||
		strings.HasPrefix(normalized, "audit_outbox_backlog_count must be between ") ||
		strings.HasPrefix(normalized, "avatar_cleanup_pending_count must be between ") ||
		strings.HasPrefix(normalized, "mail_oldest_pending_age must be a duration between ") ||
		strings.HasPrefix(normalized, "audit_oldest_pending_age must be a duration between ") {
		return "observability.configuration_invalid"
	}
	return apiErrorCodeRequestFailed
}
